### ISSUE TITLE
Deployment Question

### ISSUE THREAD

**Issue by z0ph** [danielireson/serverless-url-shortener#1]
Hi @danielireson,

Thanks for this great project! I've two questions:

- Is it possible to use custom domain name ? http/https (I'm using static web hosting for my websites with domain names on it.)
- Is it possible to use existing bucket ?

Thanks,
Have a nice day,

**Comment by danielireson** [comment]
Hi Victor, glad you like the project. 

It is possible to use a custom domain. If you're looking to have it served over https then you'll need to look into distributing it via CloudFront. Here's a [support doc](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/MigrateS3ToCloudFront.html) that you might find useful for that. 

You can also use an existing bucket, providing the correct access permissions are in place. 
1. The Lambda/api needs to have `putObject` access so it can save the redirect objects
2. There needs to be a public `GetObject` permission so that users can actually be redirected. 

You basically need to recreate the permissions defined in `serverless.yml`. But bear in mind that adding permissions may expose any existing objects that you currently have in your S3 bucket currently.

**Comment by z0ph** [comment]
Hi @danielireson,
Thanks for your answer but when I first tried to deploy, I was facing an error: "The bucket already exists" because I was using an existing bucket for this new purpose.

Is there a way to store files in a subfolder of the target bucket?

Thanks,
zoph

**Comment by danielireson** [comment]
No problem. Yes there would be a way to store the files in a sub folder on the target bucket, you'd have to look into editing functions responsible for saving in `api.js`. In regards to the error though, this is due to Serverless Framework trying to create the bucket again and you've already created it. If you remove the S3 bucket resource definition in `serverless.yml` and try again it should deploy.

**Comment by z0ph** [comment]
Great, thanks I'll look into this direction :)

**Comment by danielireson** [comment]
Good luck 👍
